services:
  - type: web
    name: velocity-telemetry
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        value: 10000
      - key: API_SECRET_KEY
        generateValue: true
